# *Indexing vs Fancy indexing*

The indexing is a way to select consecutive rows and columns or individual elementes, while the fancy indexing is for access to separate elements in the matrix, this is done using list of indexes.

There is another big difference between these two concepts. The first one always return a **view** while the second will return a **copy**.

**What the fuck that means?**

That means that if changes are done after an indexing calling those will be applied to the original matrix, on the other hand if changes are done after a fancy indexing those changes will be applied only to the submatrix called. See function index_vs_fancy() for an exemplification.

In [1]:
import numpy as np

In [16]:
def index_vs_fancy():
    
    ## indexing vs fancy indexing
    original = np.random.randint(10,size=(3,3))
    print("**original matrix**\n",original)
    view = original [:2]
    print ("**indexing: submatrix**\n", view)
    view [0,0] = 40
    print ("**after changes done to view. original matrix:**\n",original)
    copy = original [[0,1]]
    print ("**fancy indexing:submatrix**\n", copy)
    copy[0,0] = 50
    print ("**after changes done to copy. original matrix:**\n", original)
index_vs_fancy()

**original matrix**
 [[7 2 9]
 [8 8 2]
 [7 4 4]]
**indexing: submatrix**
 [[7 2 9]
 [8 8 2]]
**after changes done to view. original matrix:**
 [[40  2  9]
 [ 8  8  2]
 [ 7  4  4]]
**fancy indexing:submatrix**
 [[40  2  9]
 [ 8  8  2]]
**after changes done to copy. original matrix:**
 [[40  2  9]
 [ 8  8  2]
 [ 7  4  4]]


In [2]:
def slice_a_matrix ():
    # Playing with the indexing of numpy matrix 
    
    ## Fancy index
    
    matrix=np.random.rand(3,3)
    
    ### Access diferent elements at the same time
    # i.e. 
    elems=matrix[[0,2],0]
    print(elems)
    

slice_a_matrix()

[0.77625612 0.12099103]


In [36]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])